export type ThemeModel = keyof typeof ThemeModelSelect

export const ThemeModelSelect = {
  warnPalette: 'warnPalette',
  pinkPalette: 'pinkPalette',
  purplePalette: 'purplePalette',
  deepPurplePalette: 'deepPurplePalette',
  indigoPalette: 'indigoPalette',
  bluePalette: 'bluePalette',
  lightBluePalette: 'lightBluePalette',
  cyanPalette: 'cyanPalette',
  tealPalette: 'tealPalette',
  greenPalette: 'greenPalette',
  lightGreenPalette: 'lightGreenPalette',
  limePalette: 'limePalette',
  yellowPalette: 'yellowPalette',
  amberPalette: 'amberPalette',
  orangePalette: 'orangePalette',
  deepOrangePalette: 'deepOrangePalette',
  brownPalette: 'brownPalette',
  greyPalette: 'greyPalette',
  blueGreyPalette: 'blueGreyPalette',
  mandaditosPalette: 'mandaditosPalette',
  mandaditosAccentPalette: 'mandaditosAccentPalette',
}